package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2015-01-16T10:42:04.271+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "AvailabilityServiceSoap")
@XmlSeeAlso({com.micros.webservices.og._4_3.activity.ObjectFactory.class, com.micros.webservices.og._4_3.hotelcommon.ObjectFactory.class, com.micros.webservices.ows._5_1.areaavailability.ObjectFactory.class, org.opentravel.ota._2003._05.ObjectFactory.class, com.micros.webservices.ows._5_1.availability.ObjectFactory.class, com.micros.webservices.og._4_3.name.ObjectFactory.class, com.micros.webservices.og._4_3.membership.ObjectFactory.class, com.micros.webservices.og._4_3.core.ObjectFactory.class, com.micros.webservices.og._4_3.availability.ObjectFactory.class, com.micros.webservices.og._4_3.common.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AvailabilityServiceSoap {

    @WebResult(name = "AvailabilityCacheResponse", targetNamespace = "http://webservices.micros.com/ows/5.1/Availability.wsdl", partName = "AvailabilityCacheResult")
    @WebMethod(operationName = "AvailabilityCache", action = "http://webservices.micros.com/ows/5.1/Availability.wsdl#AvailabilityCache")
    public com.micros.webservices.ows._5_1.availability.AvailabilityCacheResponse availabilityCache(
        @WebParam(partName = "AvailabilityCacheRequest", name = "AvailabilityCacheRequest", targetNamespace = "http://webservices.micros.com/ows/5.1/Availability.wsdl")
        com.micros.webservices.ows._5_1.availability.AvailabilityCacheRequest availabilityCacheRequest
    );

    @WebResult(name = "HotelCacheChangeRS", targetNamespace = "http://webservices.micros.com/ows/5.1/Availability.wsdl", partName = "HotelCacheChangeResult")
    @WebMethod(operationName = "HotelCacheChange", action = "http://webservices.micros.com/ows/5.1/Availability.wsdl#HotelCacheChange")
    public com.micros.webservices.ows._5_1.availability.HotelCacheChangeRS hotelCacheChange(
        @WebParam(partName = "HotelCacheChangeRQ", name = "HotelCacheChangeRQ", targetNamespace = "http://webservices.micros.com/ows/5.1/Availability.wsdl")
        com.micros.webservices.ows._5_1.availability.HotelCacheChangeRQ hotelCacheChangeRQ
    );

    @WebResult(name = "FetchCalendarResponse", targetNamespace = "http://webservices.micros.com/ows/5.1/Availability.wsdl", partName = "FetchCalendarResult")
    @WebMethod(operationName = "FetchCalendar", action = "http://webservices.micros.com/ows/5.1/Availability.wsdl#FetchCalendar")
    public com.micros.webservices.ows._5_1.availability.FetchCalendarResponse fetchCalendar(
        @WebParam(partName = "FetchCalendarRequest", name = "FetchCalendarRequest", targetNamespace = "http://webservices.micros.com/ows/5.1/Availability.wsdl")
        com.micros.webservices.ows._5_1.availability.FetchCalendarRequest fetchCalendarRequest
    );

    @WebResult(name = "AreaAvailabilityResponse", targetNamespace = "http://webservices.micros.com/ows/5.1/Availability.wsdl", partName = "AreaAvailabilityResult")
    @WebMethod(operationName = "AreaAvailability", action = "http://webservices.micros.com/ows/5.1/Availability.wsdl#AreaAvailability")
    public com.micros.webservices.ows._5_1.areaavailability.AreaAvailabilityResponse areaAvailability(
        @WebParam(partName = "AreaAvailabilityRequest", name = "AreaAvailabilityRequest", targetNamespace = "http://webservices.micros.com/ows/5.1/Availability.wsdl")
        com.micros.webservices.ows._5_1.availability.AreaAvailabilityRequest areaAvailabilityRequest
    );

    @WebResult(name = "AvailabilityResponse", targetNamespace = "http://webservices.micros.com/ows/5.1/Availability.wsdl", partName = "AvailabilityResult")
    @WebMethod(operationName = "Availability", action = "http://webservices.micros.com/ows/5.1/Availability.wsdl#Availability")
    public com.micros.webservices.ows._5_1.availability.AvailabilityResponse availability(
        @WebParam(partName = "AvailabilityRequest", name = "AvailabilityRequest", targetNamespace = "http://webservices.micros.com/ows/5.1/Availability.wsdl")
        com.micros.webservices.ows._5_1.availability.AvailabilityRequest availabilityRequest,
        @WebParam(partName = "OGHeader", mode = WebParam.Mode.INOUT, name = "OGHeader", targetNamespace= "http://webservices.micros.com/og/4.3/Core/", header = true)	
	javax.xml.ws.Holder<com.micros.webservices.og._4_3.core.OGHeader> ogHeader
    );

    @WebResult(name = "MultipleAvailRS", targetNamespace = "http://webservices.micros.com/ows/5.1/Availability.wsdl", partName = "GetRateAndRTAVResult")
    @WebMethod(operationName = "GetRateAndRTAV", action = "http://webservices.micros.com/ows/5.1/Availability.wsdl#GetRateAndRTAV")
    public com.micros.webservices.ows._5_1.availability.MultipleAvailRS getRateAndRTAV(
        @WebParam(partName = "MultipleAvailRQ", name = "MultipleAvailRQ", targetNamespace = "http://webservices.micros.com/ows/5.1/Availability.wsdl")
        com.micros.webservices.ows._5_1.availability.MultipleAvailRQ multipleAvailRQ
    );
}
